---
title: "My Open Science Labs Internship Journey"
slug: "my-opensciencelabs-internship-journey"
date: 2025-01-30
authors: ["Mfonobong Uyah"]
tags: ["OpenScienceLabs", "OSL", "internship"]
categories: ["Internship", "Backend"]
description: "This blog post summarizes my internship in backend development at Open Science Labs with Ivan Ogasawara as my mentor and supervisor!"
thumbnail: "/header.png"
template: "blog-post.html"
---

# About Me

I am [Mfonobong Uyah](https://www.linkedin.com/in/mfonobong-uyah-26901620a/), a graduate of Electrical and Electronics Engineering (EEE) from the Federal University of Technology, Akure (FUTA). In June 2024, I was privileged to be accepted for an internship at Open Science Labs. This program was mentored by [Ivan Ogasawara](https://github.com/xmnlab), the founder of Open Science Labs and a seasoned professional with over 10 years of experience in open-source and 22 years of experience in software development.

# The Focus of My Internship Program

My internship at Open Science Labs was designed to be comprehensive. As such, I was introduced to:<br>
• software development project work<br>
• coding challenges<br>
• project/code reviews<br> 
• open-source events<br> 
• weekly open study group sessions<br>
• Relevant online courses<br>
• personal study sessions<br>

# My First Contribution to Open Source

My first open-source contribution was a bug fix for an issue pointed out by the linter in the Growth Forge repository. Here is a link to the PR:  https://github.com/osl-incubator/growth-forge/pull/9

As a pre-requirement for participating in the OSL internship, potential candidates are to make, at least, one simple contribution. My mentor directed me to the open ‘linter’ issue on the Growth Forge repo, informing me that it was simple enough to start with. I took a look at the issue and was able to run pre-commit hooks to fix the linter problem.

# About My Internship

During my internship program, I worked on some of the most amazing incubated and affiliated projects under the OSL umbrella. Here’s a list of the repositories I engaged with and some of my activities.

## Project Work
[Growth Forge:](https://github.com/osl-incubator/growth-forge)
My contribution to the Growth Forge repository involved creating test codes for the project’s views and models and running the respective tests, as well as recording the results. 

[OSL Website:](https://www.opensciencelabs.org)
For the OSL website repository, I engaged in backend updates of several pages, including the home, team, events, and blogs pages. I also added a few new pages such as the career page, and worked to implement a website-wide search feature. 

[Artbox:](https://github.com/osl-incubator/artbox)
I utilized the Artbox text-to-speech feature to generate audio summaries of the monthly newsletter. These audios were applied to the OSL podcast. 

Aside from coding activities and project work, I also contributed by identifying and raising issues, particularly in the Artbox repository. 

## Contribution Stats
Two statistics that define my internship contribution are: <b>21 merged pull requests</b> and Python being the dominant programming language. 

## OSL and Advent of Code Challenges
I attempted several challenges from the OSL Challenge repo including the train, padlock-secret, and money-calculation challenges. I also participated in solving Advent of Code 2024 challenges themed around finding a missing Santa using sketchy direction clues.  

## Course Completions
Continuous learning is at the core of the OSL internship program. As such, I undertook several online courses, to enhance my understanding of coding concepts and learn new things altogether. Some of the courses I undertook during my internship were: <b>Version Control with Git</b> (available on [Software Carpentry](https://swcarpentry.github.io/git-novice/)), <b>Docker Training Course for the Absolute Beginner</b> (available on [KodeKloud](https://learn.kodekloud.com/courses/docker-training-course-for-the-absolute-beginner)), and <b>Python for Everyone</b> (available on [Runestone Academy](https://runestone.academy/ns/books/published/py4e-int/index.html)).

## Open Source Events
Finding and participating in open-source events was another highlight of my internship journey. In October, I applied and received a scholarship to participate in the maiden edition of the [pyOpenSci Fall Festival](https://www.pyopensci.org/events/pyopensci-2024-fall-festival.html). This event featured interactive sessions on writing modular, clean code, building a Python package, and creating reproducible reports and presentations with Quarto and Great Tables. 

## Open Study Calls
My mentor, Ivan Ogasawara, invited me to join the LiteRev-sponsored Open Study Calls every Thursday. Here, I came across several new concepts/tools such as Retrieval-Augumented Generation (RAG), JupyterLabs, etc.

After participating in more than 20 Open Study Calls, I built a culture of learning, was exposed to expert suggestions and reviews, and came across relevant courses and resources on coding and software development in general. 

## Impact of the Open Source and Open Science Community #

Support from the open-source and open-science community proved handy throughout my internship at Open Science Labs. The OSL Discord server was a place where I could throw questions and get prompt and helpful responses from a number of experts. This significantly lightened the burden of finding my footing as a beginner in software development. 

## Lessons Learnt #

There are numerous lessons to be learnt from an impactful internship like the one I had at Open Science Labs (OSL). I’ll share them with you.

• <b>Be Open to Corrections:</b>
Seek corrections. At the beginning, it might be difficult or overwhelming. However, with time, you will be grateful for it. Having someone to correct you will only make your learning process easy as you can quickly move on from mistakes and avoid them in the future. 

• <b>Be Upfront about Challenges:</b>
The Open Science Labs internship is designed to be safe, warm, and welcoming. If you happen to have challenges during the program, it is okay to speak up about it. In fact, you should speak up about it. This will help your mentor/program coordinator make necessary adjustments, enabling your continued participation and progress. 

• <b>Put Your Mind In the Work:</b>
If you like your work, it becomes easier. One notable way to build this liking is to put your mind to it. Your focus will easily translate into an interest, improving the quality of your participation and your output in general.