site_name: Open Science Labs
site_url: https://opensciencelabs.org

docs_dir: pages
site_dir: build

theme:
  name: null
  custom_dir: "theme/"
  features:
    - content.code.copy
  palette:
    primary: indigo

extra_css:
  - css/style.css
  - css/index.css

extra_javascript:
  - js/bundle.js
  - js/search.js
  - js/index.json

nav:
  - Blog: "blog/index.md"
  # - Affiliations:
  #     - index: affiliations/index.md
  - Projects:
      - index: "projects/index.md"
      - Incubation: "projects/incubation/index.md"
      - Affiliation:
          - index: "projects/affiliation/index.md"
      - All Projects: "projects/list/index.md"
  - Opportunities:
      - index: opportunities/index.md
      - Open Source Internship:
          - index: "opportunities/internship/index.md"
          - Interns Guide: "opportunities/internship/guides/interns/index.md"
          - Mentors Guide: "opportunities/internship/guides/mentors/index.md"
          - "TEMPLATE: Projects Ideas": "opportunities/internship/templates/projects-ideas.md"
          - "TEMPLATE: Intern Project Proposal": "opportunities/internship/templates/intern-proposal.md"
      - GSoC:
          - index: "opportunities/gsoc/index.md"
          - Contributor Guide: "opportunities/gsoc/guides/contributor/index.md"
          - "TEMPLATE: Contributor Project Proposal": "opportunities/gsoc/templates/contributor-proposal.md"
  - Partnership:
      - index: "partnership/index.md"
      - Partners: "partnership/partners/index.md"
  - Events:
      - index: events/index.md
  - Guidelines:
      - index: guidelines/index.md
      - Articles: guidelines/articles/index.md
      - DEI: guidelines/dei/index.md
      - Mentoring: guidelines/mentoring/index.md
  - About:
      - index: "about/index.md"
      - About OSL: "about/index.md"
      - Our Formula: "about/formula/index.md"
      - Team: about/team/index.md
      - Roadmap: about/roadmap/index.md
      - Governance: about/governance/index.md
      - CoC: about/coc/index.md
  - Donate: "donate/index.md"

markdown_extensions:
  - toc:
      permalink: " #"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - include-markdown:
      start: <!-- start -->
      end: <!-- end -->

  - blogging:
      template: theme/blog-list.html
      dirs:
        - blog
      features:
        tags: {}

  - rss:
      abstract_chars_count: 160 # -1 for full content
      abstract_delimiter: <!-- more -->
      categories:
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d"
        default_timezone: Europe/Paris
        default_time: "09:30"
      enabled: true
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 20
      pretty_print: false
      match_path: ".*"
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
