site_name: Open Science Labs
site_url: https://opensciencelabs.org

docs_dir: pages
site_dir: build

extra:
  enumerate: !!python/name:builtins.enumerate

theme:
  name: null
  custom_dir: "theme/"
  features:
    - content.code.copy
  palette:
    primary: indigo

extra_css:
  - css/base.css
  - css/blog.css
  - css/code.css
  - css/content.css
  - css/footer.css
  - css/home.css
  - css/nav.css
  - css/search.css
  - css/tokens.css
  - css/utilities.css

extra_javascript:
  - js/theme.js
  - js/osl-search.js
  - js/vendor/lunr.min.js
  - js/vendor/lunr.stemmer.support.min.js
  - js/vendor/lunr.multi.min.js
  - js/vendor/lunr.es.min.js
  - js/vendor/lunr.pt.min.js

nav:
  - Blog: "blog/index.md"
  - Projects:
      - Overview: "projects/index.md"
      - Incubation: "projects/incubation/index.md"
      - Affiliation: "projects/affiliation/index.md"
      - All Projects: "projects/list/index.md"
  - Opportunities:
      - Overview: opportunities/index.md
      - OSS Internship:
          - Overview: "opportunities/internships/oss/index.md"
          - Project Ideas: "opportunities/internships/oss/project-ideas/index.md"
          - "Contribution Guidelines": "opportunities/guides/contribution/index.md"
          - "Candidates' Guide": "opportunities/internships/guides/interns/index.md"
          - "Template: Projects Ideas": "opportunities/internships/templates/projects-ideas/index.md"
          - "Template: Candidates's Project Proposal": "opportunities/internships/templates/candidate-proposal/index.md"
      - OSS Research Seed Internship:
          - Overview: "opportunities/internships/oss-research-seed/index.md"
          - Project Ideas: "opportunities/internships/oss-research-seed/project-ideas/index.md"
          - "Contribution Guidelines": "opportunities/guides/contribution/index.md"
          - "Candidates' Guide": "opportunities/internships/guides/interns/index.md"
          - "Template: Projects Ideas": "opportunities/internships/templates/projects-ideas/index.md"
          - "Template: Candidates's Project Proposal": "opportunities/internships/templates/candidate-proposal/index.md"
      - Google Summer of Code:
          - Overview: "opportunities/gsoc/index.md"
          - Project Ideas: "opportunities/gsoc/project-ideas/index.md"
          - "Contribution Guidelines": "opportunities/guides/contribution/index.md"
          - "Candidates' Guide": "opportunities/gsoc/guides/contributor/index.md"
          - "Template: Project Idea": "opportunities/gsoc/templates/project-ideas.md"
          - "Template: Candidates Project Proposal": "opportunities/gsoc/templates/contributor-proposal.md"
  - Partnership:
      - Overview: "partnership/index.md"
      - Partners: "partnership/partners/index.md"
      - Open Proposals:
          - Overview: "partnership/open-proposals/index.md"
          - Community Training: "partnership/open-proposals/community-training/index.md"
  - Learning:
      - Overview: learning/index.md
      - Events: learning/events/index.md
      - Study Groups: learning/study-groups/index.md
  - About:
      - Overview: "about/index.md"
      - About OSL:
          - Overview: "about/index.md"
          - Contact Us: about/contact/index.md
          - Our Formula: "about/formula/index.md"
          - Roadmap: about/roadmap/index.md
          - Code Of Conduct: about/coc/index.md
          - Governance: about/governance/index.md
      - Team: about/team/index.md
      - Fiscal Sponsor: about/fiscal-sponsor/index.md
      - Guidelines:
          - Overview: about/guidelines/index.md
          - Articles: about/guidelines/articles/index.md
          - DEI: about/guidelines/dei/index.md
          - Mentoring: about/guidelines/mentoring/index.md
  - Donate: "donate/index.md"

markdown_extensions:
  - toc:
      permalink: " #"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_truly_sane_lists

plugins:
  - include-markdown:
      start: <!-- start -->
      end: <!-- end -->

  - blogging:
      template: theme/blog-list.html
      dirs:
        - blog
      features:
        tags: {}

  - rss:
      abstract_chars_count: 160 # -1 for full content
      abstract_delimiter: <!-- more -->
      categories:
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d"
        default_timezone: Europe/Paris
        default_time: "09:30"
      enabled: true
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 20
      pretty_print: false
      match_path: ".*"
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: false
      type: iso_date

  - search:
      lang:
        - en
        - es
        - pt
      prebuild_index: true
