name: osl-web
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python <3.12
  - pip
  - pip:
    - pre-commit
    - mkdocs ==1.4.2
    - makim ==1.14
    - mkdocs-blogging-plugin
    - mkdocs-rss-plugin <1.9.0
    - jupyterlab
    - nbconvert
    - pymdown-extensions
