name: osl-web
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python
  - mkdocs
  - mkdocs-jupyter
  - pre-commit
  - pip
  - pip:
    - makim
    - mkdocs-blogging-plugin
    - mkdocs-rss-plugin
