name: osl-web
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python <3.12
  - mkdocs 1.4.2
  - mkdocs-jupyter
  - pre-commit
  - pip
  - pip:
    - mkdocs==1.4.2
    - makim
    - mkdocs-blogging-plugin
    - mkdocs-rss-plugin
