version: 1.0
compose-app: docker compose
env-file: .env
defaults:
  group: {{ env.KXGR_GROUP }}
  project-name: sugar-{{ env.KXGR_PROJECT_NAME }}
services:
  project-name: project1  # optional
  compose-path: tests/containers/group1/compose.yaml
  env-file: .env
  default: service1-1,service1-3
  available:
    - name: service1-1
    - name: service1-2
    - name: service1-3
