
name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.event_name }}-${{ github.ref }}
      cancel-in-progress: true
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        environment-file: conda/dev.yaml
        channels: conda-forge,nodefaults
        activate-environment: osl-web
        auto-update-conda: true
        conda-solver: libmamba

    - name: Build the book
      run: |
        makim pages.build
        echo "opensciencelabs.org" > build/CNAME

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      if: ${{ github.event_name == 'push' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
